# Generated by Django 5.2.17 on 2026-08-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_index', models.IntegerField()),
                ('planet', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['phase_index'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.phase')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.plan'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('est_minutes', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True, default='')),
                ('systems_init', models.CharField(blank=True, default='', max_length=200)),
                ('observed', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.day')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('plan', 'phase_index')},
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase_index', models.IntegerField(default=0)),
                ('current_day_index', models.IntegerField(default=1)),
                ('completed_tasks', models.JSONField(default=dict)),
                ('completed_days', models.JSONField(default=dict)),
                ('completed_phases', models.JSONField(default=dict)),
                ('phase_unlocked', models.JSONField(default=list)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
