# Generated by Django 5.2.17 on 2026-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
