"""
Database models for Cosmos Lab.
Replaces Firestore collections (users, plans, progress) with relational tables.
"""
from django.db import models
from django.contrib.auth.models import User
import json
from typing import TYPE_CHECKING


class Plan(models.Model):
    """A learning roadmap generated by the AI, owned by a user."""
    if TYPE_CHECKING:
        id: int
        phases: models.Manager['Phase']
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='plans', null=True, blank=True)
    topic = models.CharField(max_length=500)
    status = models.CharField(max_length=50, default='confirmed')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.topic} ({self.user})"

    def to_dict(self):
        """Serialize to the same JSON structure the frontend expects."""
        return {
            'id': self.id,
            'topic': self.topic,
            'status': self.status,
            'phases': [phase.to_dict() for phase in self.phases.all().order_by('phase_index')],
        }


class Phase(models.Model):
    """One phase of a plan, mapped to a planet."""
    if TYPE_CHECKING:
        days: models.Manager['Day']
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name='phases')
    phase_index = models.IntegerField()
    planet = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    summary = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['phase_index']
        unique_together = ['plan', 'phase_index']

    def __str__(self):
        return f"Phase {self.phase_index}: {self.title}"

    def to_dict(self):
        return {
            'phaseIndex': self.phase_index,
            'planet': self.planet,
            'title': self.title,
            'summary': self.summary,
            'days': [day.to_dict() for day in self.days.all().order_by('day_index')],
        }


class Day(models.Model):
    """A single day within a phase."""
    if TYPE_CHECKING:
        tasks: models.Manager['Task']
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE, related_name='days')
    day_index = models.IntegerField()

    class Meta:
        ordering = ['day_index']

    def __str__(self):
        return f"Day {self.day_index}"

    def to_dict(self):
        return {
            'dayIndex': self.day_index,
            'date': None,
            'tasks': [task.to_dict() for task in self.tasks.all()],
        }


class Task(models.Model):
    """A single task within a day."""
    day = models.ForeignKey(Day, on_delete=models.CASCADE, related_name='tasks')
    task_id = models.CharField(max_length=50)  # e.g. "t1-1"
    title = models.CharField(max_length=500)
    tags = models.JSONField(default=list)
    est_minutes = models.IntegerField(default=60)
    description = models.TextField(blank=True, default='')
    resource_links = models.JSONField(default=list, blank=True)
    systems_init = models.CharField(max_length=200, blank=True, default='')
    observed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.task_id}: {self.title}"

    def to_dict(self):
        return {
            'id': self.task_id,
            'title': self.title,
            'tags': self.tags,
            'estMinutes': self.est_minutes,
            'description': self.description,
            'resourceLinks': self.resource_links,
            'systemsInit': self.systems_init,
            'observed': self.observed,
        }


class Progress(models.Model):
    """
    Tracks a user's progress through a plan.
    Uses JSON fields for flexible nested data (completed tasks, days, phases).
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='progress_records')
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name='progress_records')
    current_phase_index = models.IntegerField(default=0)
    current_day_index = models.IntegerField(default=1)
    # JSON: { "phaseIndex_dayIndex_taskId": { "done": true, "note": "", "loggedMinutes": 0, "completedAt": timestamp } }
    completed_tasks = models.JSONField(default=dict)
    # JSON: { "phaseIndex_dayIndex": true }
    completed_days = models.JSONField(default=dict)
    # JSON: { "phaseIndex": true }
    completed_phases = models.JSONField(default=dict)
    # JSON: [true, false, false, ...]
    phase_unlocked = models.JSONField(default=list)
    current_streak = models.IntegerField(default=0)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['user', 'plan']

    def __str__(self):
        return f"Progress for {self.user} on {self.plan.topic}"

    def to_dict(self):
        return {
            'currentPhaseIndex': self.current_phase_index,
            'currentDayIndex': self.current_day_index,
            'completedTasks': self.completed_tasks,
            'completedDays': self.completed_days,
            'completedPhases': self.completed_phases,
            'phaseUnlocked': self.phase_unlocked,
            'currentStreak': self.current_streak,
            'lastUpdated': int(self.last_updated.timestamp() * 1000) if self.last_updated else 0,
        }
